version: "3.7"
services:
     # Collecting and querying data with the powerful elk search engine 
    elasticsearch:
      build:
        context: elasticsearch/
        args:
          ELK_VERSION: $ELK_VERSION
      volumes:
        - type: bind
          source: ./elasticsearch/config/elasticsearch.yml
          target: /usr/share/elasticsearch/config/elasticsearch.yml
          read_only: true
        - type: volume
          source: elasticsearch
          target: /usr/share/elasticsearch/data
      ports:
        - "9200:9200"
        - "9300:9300"
      environment:
        ES_JAVA_OPTS: "-Xmx256m -Xms256m"
        ELASTIC_PASSWORD: changeme
        # Use single node discovery in order to disable production mode and avoid bootstrap checks.
        # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
        discovery.type: single-node
      networks:
        - elastic

    # create powerful visualizations with kibana
    kibana:
      build:
        context: kibana/
        args:
          ELK_VERSION: $ELK_VERSION
      volumes:
        - type: bind
          source: ./kibana/config/kibana.yml
          target: /usr/share/kibana/config/kibana.yml
          read_only: true
      ports:
        - "5601:5601"
      networks:
        - elastic
      depends_on:
        - elasticsearch

    # shipping data into elasticsearch with logstash
    logstash:
      build:
        context: logstash/
        args:
          ELK_VERSION: $ELK_VERSION      
      command: logstash -f logstash.conf
      container_name: logstash
      environment:
        XPACK_MONITORING_ENABLED: "true"
        XPACK_MONITORING_ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      ports:
       - "5043:5043"
       - "5044:5044"
      networks:
        - elastic
      depends_on:
        - elasticsearch


    # Spting boot app
    spring_boot_app:
      build:
        context: ./spring-boot-app
      ports:
        - "8080:8080"
      networks:
        - elastic

volumes:
  elasticsearch:
networks:
  elastic:
    driver: bridge
